"""
Simplified postprocessing module for agent responses.
Contains essential functions for cleaning and formatting generated responses.
"""

from agent_logging import get_logger

logger = get_logger('postprocessor')

# Constants for consistent behavior
MIN_SENTENCE_LENGTH = 30
MIN_CONTEXT_LENGTH = 20
DANGLING_REMOVAL_ATTEMPTS = 3
PUNCTUATION_ENDINGS = ('.', '!', '?')

# Essential prepositions
ESSENTIAL_PREPOSITIONS = {
    "a", "ante", "bajo", "cabe", "con", "contra", "de", "desde", "durante", "en", "entre", 
    "hacia", "hasta", "mediante", "para", "por", "segun", "sin", "so", "sobre", "tras",
    "al", "del", "pa", "pel"
}

def _find_last_sentence_end(text):
    """Find the last sentence ending position in text."""
    return max(text.rfind("."), text.rfind("!"), text.rfind("?"))

def _sanitize_text(text):
    """Normalize whitespace in text."""
    return " ".join(str(text).strip().split())

def is_response_cut_off(text):
    """Detects if a response is cut off or incomplete."""
    if not text or len(text.strip()) < 10:
        return False
    
    s = text.strip()
    
    # Discard if contains metadata
    if ("(" in s and ")" in s and any(c.isdigit() for c in s)) or "Total:" in s:
        return False
    
    # Clear cut-off indicators
    cut_off_indicators = [
        "..." in s or "…" in s,
        s.endswith((" y ", " o ", " pero ", " que ", " para ", " por ", " con ", " de ", " en ", " a ")),
        len(s) > 15 and s[-1].islower() and s[-1] not in ".!?,"
    ]
    
    return any(cut_off_indicators)

def ends_dangling(sentence: str) -> bool:
    """Detects if a sentence ends with a dangling preposition."""
    if not sentence:
        return False
    
    last = sentence.rstrip(".!? ").strip().split(" ")[-1].lower() if sentence.strip() else ""
    return last in ESSENTIAL_PREPOSITIONS or len(last) == 1

def postprocess_response(text, max_chars=280):
    """
    Post-processes an LLM response in a simplified way.
    
    Args:
        text: Original text generated by the LLM
        max_chars: Maximum allowed character limit
        
    Returns:
        Clean and formatted text
    """
    if not text:
        return ""
    
    # First check if it's internal thinking and reject immediately
    if is_internal_thinking(text):
        logger.warning(f"🧠 Internal thinking detected and rejected: {text[:100]}...")
        return ""  # Return empty so system uses fallback
    
    s = _sanitize_text(text)
    
    # Fix cut-off response
    if is_response_cut_off(s):
        last_end = _find_last_sentence_end(s)
        if last_end >= MIN_SENTENCE_LENGTH:
            s = s[:last_end + 1].rstrip()
        else:
            last_space = s.rfind(" ")
            s = (s[:last_space] if last_space >= MIN_SENTENCE_LENGTH else s).rstrip()
    
    # Limit length
    if len(s) > max_chars:
        recorte = s[:max_chars]
        last_end = _find_last_sentence_end(recorte)
        if last_end >= MIN_SENTENCE_LENGTH:
            s = recorte[:last_end + 1].rstrip()
        else:
            last_space = recorte.rfind(" ")
            s = (recorte[:last_space] if last_space >= MIN_SENTENCE_LENGTH else recorte).rstrip()
    
    # Ensure final punctuation only if necessary
    if s and s[-1] not in PUNCTUATION_ENDINGS:
        s = s + "!"
    
    # Remove dangling phrases
    if ends_dangling(s):
        base = s.rstrip(".!? ").strip()
        last_end = _find_last_sentence_end(base)
        if last_end >= MIN_CONTEXT_LENGTH:
            base = base[:last_end + 1].rstrip(".!? ")
        else:
            # Remove last words until no longer dangling
            for _ in range(DANGLING_REMOVAL_ATTEMPTS):
                if not ends_dangling(base):
                    break
                cut = base.rfind(" ")
                if cut < 0:
                    base = ""
                    break
                base = base[:cut].rstrip()
        
        s = base.strip()
        # Add punctuation only if it doesn't have it already
        if s and s[-1] not in PUNCTUATION_ENDINGS:
            s = s + "!"
    
    return s

def consolidate_context(history_list, max_interactions=5, personality=None):
    """Consolidates conversation history in a simplified way."""
    if not history_list:
        return ""

    def _sanitize(text, limit=240):
        s = _sanitize_text(text)
        if len(s) > limit:
            return s[:limit].rstrip() + "..."
        return s

    # Use provided personality or default values
    if personality is None:
        personality = {}
    
    keywords = personality.get("history_keywords", [])
    important_label = personality.get("context_important_label", "CONTEXTO IMPORTANTE")
    human_label = personality.get("context_labels", {}).get("human", "Humano")
    bot_label = personality.get("context_labels", {}).get("bot", "Bot")

    important_interactions = []
    normal_interactions = []

    for h in history_list:
        bot_text = (h.get("bot", "") or "").lower()
        human_text = (h.get("humano", "") or "").lower()

        is_important = any(kw in bot_text or kw in human_text for kw in keywords)

        if is_important:
            important_interactions.append(h)
        else:
            normal_interactions.append(h)

    entries = []

    if important_interactions:
        h = important_interactions[-1]
        human = _sanitize(h.get("humano", ""), limit=240)
        bot = _sanitize(h.get("bot", ""), limit=240)
        if human or bot:
            parts = [f"[{important_label}]"]
            if human:
                parts.append(f"{human_label}: {human}")
            if bot:
                parts.append(f"{bot_label}: {bot}")
            entries.append("\n".join(parts))

    latest_normal = (
        normal_interactions[-(max_interactions - 1):]
        if important_interactions
        else normal_interactions[-max_interactions:]
    )

    for h in latest_normal:
        human = _sanitize(h.get("humano", ""), limit=240)
        bot = _sanitize(h.get("bot", ""), limit=240)
        if human or bot:
            parts = []
            if human:
                parts.append(f"{human_label}: {human}")
            if bot:
                parts.append(f"{bot_label}: {bot}")
            entries.append("\n".join(parts))

    return "\n\n".join(entries) if entries else ""

def is_internal_thinking(text):
    """Detects if text is internal LLM thinking rather than an in-character response."""
    if not text:
        return False
    
    text_lower = text.lower().strip()
    
    # Patterns that indicate internal thinking (consolidated)
    internal_thinking_patterns = [
        "wait, let's",
        "let me think",
        "let me check",
        "let's use",
        "if possible",
        "or just",
        "maybe we should",
        "i think",
        "perhaps",
        "considering",
        "analyzing",
        "evaluating",
        "let me consider",
        "we could",
        "maybe use",
        "should we",
        "let me see",
        "wait, let me",
        "let me just",
        "maybe i should",
        "i should",
        "we need to",
        "we have to",
        "it might be",
        "it could be",
        "let's see",
        "let me think about",
        "i need to",
        "maybe we can",
        "perhaps we could"
    ]
    
    # Check if contains any of the patterns
    for pattern in internal_thinking_patterns:
        if pattern in text_lower:
            return True
    
    # Check if very short and seems incomplete
    if len(text.strip()) < 20 and any(word in text_lower for word in ["wait", "let", "maybe", "perhaps", "could", "should"]):
        return True
    
    return False

def is_blocked_response(text):
    """Detects LLM rejection messages."""
    if not text:
        return False
    
    s = _sanitize_text(text)
    blocked_phrases = [
        "soy un asistente virtual",
        "no puedo ayudar",
        "no puedo hacer",
        "no estoy autorizado",
        "i cannot",
        "cannot help",
        "i'm sorry, i can't"
    ]
    
    return any(phrase in s for phrase in blocked_phrases)
