"""
Simplified postprocessing module for agent responses.
Contains essential functions for cleaning and formatting generated responses.
"""

from agent_logging import get_logger

logger = get_logger('postprocessor')

# Constants for consistent behavior
MIN_SENTENCE_LENGTH = 30
MIN_CONTEXT_LENGTH = 20
DANGLING_REMOVAL_ATTEMPTS = 3

# Essential prepositions
ESSENTIAL_PREPOSITIONS = {
    "a", "ante", "bajo", "cabe", "con", "contra", "de", "desde", "durante", "en", "entre", 
    "hacia", "hasta", "mediante", "para", "por", "segun", "sin", "so", "sobre", "tras",
    "al", "del", "pa", "pel"
}

def _find_last_sentence_end(text):
    """Find the last sentence ending position in text."""
    return max(text.rfind("."), text.rfind("!"), text.rfind("?"))

def _sanitize_text(text):
    """Normalize whitespace in text."""
    return " ".join(str(text).strip().split())

def is_response_cut_off(text):
    """Detects if a response is cut off or incomplete."""
    if not text or len(text.strip()) < 10:
        return False
    
    s = text.strip()
    
    # Discard if contains metadata
    if ("(" in s and ")" in s and any(c.isdigit() for c in s)) or "Total:" in s:
        return False
    
    # Clear cut-off indicators
    cut_off_indicators = [
        "..." in s or "…" in s,
        s.endswith((" y ", " o ", " pero ", " que ", " para ", " por ", " con ", " de ", " en ", " a ")),
        len(s) > 15 and s[-1].islower() and s[-1] not in ".!?,"
    ]
    
    return any(cut_off_indicators)

def ends_dangling(sentence: str) -> bool:
    """Detects if a sentence ends with a dangling preposition."""
    if not sentence:
        return False
    
    last = sentence.rstrip(".!? ").strip().split(" ")[-1].lower() if sentence.strip() else ""
    return last in ESSENTIAL_PREPOSITIONS or len(last) == 1

def postprocess_response(text, max_chars=280):
    """
    Post-processes an LLM response in a simplified way.
    
    Args:
        text: Original text generated by the LLM
        max_chars: Maximum allowed character limit
        
    Returns:
        Clean and formatted text
    """
    if not text:
        return ""
    
    # First check if it's internal thinking and reject immediately
    if is_internal_thinking(text):
        logger.warning(f"🧠 Internal thinking detected and rejected: {text[:100]}...")
        return ""  # Return empty so system uses fallback
    
    s = _sanitize_text(text)
    
    # Fix cut-off response
    if is_response_cut_off(s):
        last_end = _find_last_sentence_end(s)
        if last_end >= MIN_SENTENCE_LENGTH:
            s = s[:last_end + 1].rstrip()
        else:
            last_space = s.rfind(" ")
            s = (s[:last_space] if last_space >= MIN_SENTENCE_LENGTH else s).rstrip()
    
    # Limit length
    if len(s) > max_chars:
        recorte = s[:max_chars]
        last_end = _find_last_sentence_end(recorte)
        if last_end >= MIN_SENTENCE_LENGTH:
            s = recorte[:last_end + 1].rstrip()
        else:
            last_space = recorte.rfind(" ")
            s = (recorte[:last_space] if last_space >= MIN_SENTENCE_LENGTH else recorte).rstrip()
    
    # Remove dangling phrases
    if ends_dangling(s):
        base = s.rstrip(".!? ").strip()
        last_end = _find_last_sentence_end(base)
        if last_end >= MIN_CONTEXT_LENGTH:
            base = base[:last_end + 1].rstrip(".!? ")
        else:
            # Remove last words until no longer dangling
            for _ in range(DANGLING_REMOVAL_ATTEMPTS):
                if not ends_dangling(base):
                    break
                cut = base.rfind(" ")
                if cut < 0:
                    base = ""
                    break
                base = base[:cut].rstrip()
        
        s = base.strip()
    
    return s

def consolidate_context(history_list, max_interactions=5, personality=None, role=None, server=None):
    """Consolidates conversation history with subrole prompt injection for keyword matches."""
    if not history_list:
        return ""

    def _sanitize(text, limit=240):
        s = _sanitize_text(text)
        if len(s) > limit:
            return s[:limit].rstrip() + "..."
        return s

    # Use provided personality or default values
    if personality is None:
        personality = {}
    
    human_label = personality.get("context_labels", {}).get("human", "Humano")
    bot_label = personality.get("context_labels", {}).get("bot", "Bot")

    # Putre/template history format: match the prompt layout used in logs/examples.
    # Keep oro/beggar injection out of history (handled in build_prompt bottom context block).
    history_label = (personality.get("context_history_label") or "").strip().lower()
    use_template_format = history_label in {"istorial", "historial"}

    recent = history_list[-max_interactions:]
    entries: list[str] = []

    if use_template_format:
        header_tpl = personality.get("history_header_template")
        if not isinstance(header_tpl, str) or not header_tpl.strip():
            header_tpl = "[{n} LAST INTERACTIONS WITH THE HUMAN]"
        entries.append(header_tpl.format(n=max_interactions))

    for h in recent:
        human = _sanitize(h.get("humano", ""), limit=240)
        bot = _sanitize(h.get("bot", ""), limit=240)
        if human:
            entries.append(f"{human_label}: {human}")
        if bot:
            entries.append(f"{bot_label}: {bot}")
        if use_template_format:
            entries.append("")

    if use_template_format:
        while entries and entries[-1] == "":
            entries.pop()

    return "\n".join(entries).strip()

def is_internal_thinking(text):
    """Detects if text is internal LLM thinking rather than an in-character response."""
    if not text:
        return False
    
    text_lower = text.lower().strip()
    
    # Patterns that indicate internal thinking (consolidated)
    internal_thinking_patterns = [
        "wait, let's",
        "let me think",
        "let me check",
        "let's use",
        "if possible",
        "or just",
        "maybe we should",
        "i think",
        "perhaps",
        "considering",
        "analyzing",
        "evaluating",
        "let me consider",
        "we could",
        "maybe use",
        "should we",
        "let me see",
        "wait, let me",
        "let me just",
        "maybe i should",
        "i should",
        "we need to",
        "we have to",
        "it might be",
        "it could be",
        "let's see",
        "let me think about",
        "i need to",
        "maybe we can",
        "perhaps we could"
    ]
    
    # Check if contains any of the patterns
    for pattern in internal_thinking_patterns:
        if pattern in text_lower:
            return True
    
    # Check if very short and seems incomplete
    if len(text.strip()) < 20 and any(word in text_lower for word in ["wait", "let", "maybe", "perhaps", "could", "should"]):
        return True
    
    return False

def is_blocked_response(text):
    """Detects LLM rejection messages."""
    if not text:
        return False
    
    s = _sanitize_text(text)
    blocked_phrases = [
        "soy un asistente virtual",
        "no puedo ayudar",
        "no puedo hacer",
        "no estoy autorizado",
        "i cannot",
        "cannot help",
        "i'm sorry, i can't"
    ]
    
    return any(phrase in s for phrase in blocked_phrases)

def is_readme_response(text):
    """Detects if the LLM responded with 'README' following the golden rule - more relaxed detection."""
    if not text:
        return False
    
    s = _sanitize_text(text).upper()
    
    # Check if README appears as a standalone word
    import re
    if not re.search(r'\bREADME\b', s):
        return False
    
    # Relaxed detection: accept any response containing README
    # Remove strict length and character requirements to catch subtle mentions
    # The old logic was too restrictive and missed cases like "README!" in character responses
    
    # Only exclude obvious false positives: very long, formal responses that don't look like character responses
    if len(s) > 200:  # Increased from 60 to 200
        return False
    
    # Check if it looks like a formal/helpful response (likely false positive)
    formal_patterns = [
        "here is the readme",
        "this is the readme", 
        "the readme contains",
        "please read the readme",
        "you can find the readme",
        "below is the readme"
    ]
    
    s_lower = s.lower()
    is_formal = any(pattern in s_lower for pattern in formal_patterns)
    
    # Accept if it's not a formal response
    return not is_formal
