name: Sync to Google Cloud Storage
on:
  push:
    branches: [ main, develop, feature/*, 0.6.* ] # Añade los patrones de ramas que uses

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Sync Files'
        run: |
          gsutil -m rsync -r -d . gs://roleagentbot/${{ github.ref_name }}/
# Test push for GCP sync workflow
